language: php
sudo: false
php:
  - 5.6
  - hhvm
  - 7.0
  - nightly

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ || true
  - phpunit

cache:
  directories:
    - vendor/
