language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ || true
  - phpunit
